name: All the articles workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with all the articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Keepalive
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          output_only: true
          feed_list: "https://dev.to/feed/gautamkrishnar"
      - run: cat /tmp/blog_post_workflow_output.json
        
