name: Test
on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          curl https://oluwatobi.dev/blog/feed
